import os
from typing import List
from pydantic import BaseModel
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.document_loaders import TextLoader
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq
from dotenv import load_dotenv

# Load API keys from environment variables
load_dotenv()
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")

#---------------------------------------------------------------------------
# 1. Prepare VectorStore (Knowledge Base)
#---------------------------------------------------------------------------

# Load research data from a text file
docs = TextLoader("../research_notes.txt", encoding="utf-8").load()

# Split long documents into smaller chunks (500 chars each) to help the model find precise info
splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = splitter.split_documents(docs)

# Convert text chunks into vector embeddings and store them in FAISS (a fast vector database)
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vectorestore = FAISS.from_documents(chunks, embeddings)
retriever = vectorestore.as_retriever()

# Initialize our LLM (Large Language Model)
# Note: Ensure the model name is correct for your environment
llm = ChatGroq(model_name="openai/gpt-oss-120b")

#---------------------------------------------------------------------------
# 2. State Definition (Agent Memory)
#---------------------------------------------------------------------------
# The state object defines what information is tracked as the graph executes
class RAGReflectionState(BaseModel):
    question: str                  # The original user query
    retrieved_docs: List[Document] = [] # Storage for documents found during retrieval
    answer: str = ""               # The draft/final answer generated by LLM
    reflection: str = ""           # The LLM's own evaluation of its answer
    revised: bool = False          # Flag to trigger a retry if the answer is poor
    attempts: int = 0             # Track how many times we've tried to answer

#---------------------------------------------------------------------------
# 3. Graph Nodes (The "Brain" of each step)
#---------------------------------------------------------------------------

# Node A: Retrieval - Searches for relevant context
def retrieve_docs(state: RAGReflectionState) -> RAGReflectionState:
    """Uses the question to find relevant chunks in the vector store."""
    docs = retriever.invoke(state.question)
    return state.model_copy(update={"retrieved_docs": docs})

# Node B: Generation - Writes an initial answer
def generate_answer(state: RAGReflectionState) -> RAGReflectionState:
    """Generates an answer based on the retrieved documents."""
    context = "\n\n".join([doc.page_content for doc in state.retrieved_docs])
    prompt = f"""
    Use the following context to answer the question.
    
    Context:
    {context}

    Question:
    {state.question}
    """
    answer = llm.invoke(prompt).content.strip()
    return state.model_copy(update={"answer": answer, "attempts": state.attempts + 1})

# Node C: Reflection - Critiques the generated answer
def reflect_on_answer(state: RAGReflectionState) -> RAGReflectionState:
    """The LLM looks at its own answer and decides if it's 'good enough'."""
    prompt = f"""
        Reflect on the following answer to see if it fully addresses the question.
        State YES if it is complete and correct, or NO with an explanation.

        Question: {state.question}
        Answer: {state.answer}

        Respond in this format:
        Reflection: YES or NO
        Explanation: [Your reasoning here]
    """
    result = llm.invoke(prompt).content
    # Determine if we need to revise based on LLM's self-critique
    is_ok = "reflection: yes" in result.lower()
    return state.model_copy(update={"reflection": result, "revised": not is_ok})

# Node D: Finalizer - Just a placeholder to mark the end of processing
def finalize(state: RAGReflectionState) -> RAGReflectionState:
    return state

#---------------------------------------------------------------------------
# 4. Build LangGraph (The Workflow)
#---------------------------------------------------------------------------

# Initialize the graph builder with our custom state
builder = StateGraph(RAGReflectionState)

# Define all possible steps (nodes) in the workflow
builder.add_node("retriever", retrieve_docs)
builder.add_node("responder", generate_answer)
builder.add_node("reflector", reflect_on_answer)
builder.add_node("done", finalize)

# Define the flow of execution
builder.set_entry_point("retriever") # Start here

builder.add_edge("retriever", "responder") # Then go to responder
builder.add_edge("responder", "reflector") # Then go to reflector

# Add conditional routing logic:
# If the answer is good (not revised) OR we've hit 2 attempts, finish.
# Otherwise, go back to the retriever to find better info.
builder.add_conditional_edges(
    "reflector",
    lambda s: "done" if not s.revised or s.attempts >= 2 else "retriever"
)

# Connect final node to the end of the graph
builder.add_edge("done", END)

# Compile everything into an executable application
graph = builder.compile()

#---------------------------------------------------------------------------
# 5. Execution Block
#---------------------------------------------------------------------------
if __name__ == "__main__":
    # Example query with some complex requirements
    user_query = "What are the additional experiments in transformer evaluation?"
    init_state = RAGReflectionState(question=user_query)
    
    # Run the agentic workflow
    result = graph.invoke(init_state)

    print("\n" + "="*50)
    print("FINAL ANSWER:\n", result["answer"])
    print("-" * 50)
    print("REFLECTION LOG:\n", result["reflection"])
    print("-" * 50)
    print(f"Total Attempts: {result['attempts']}")
    print("="*50)